version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hooolaaa"
      - run: | 
         circleci-agent step halt
         echo "aaaaa"
         exit 0
